# Generated by Django 3.0.5 on 2021-01-24 06:01

from django.db import migrations, models
import djongo.models.fields
import matchup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', djongo.models.fields.EmbeddedField(model_container=matchup.models.MatchModel)),
                ('match_image', models.FileField(blank=True, upload_to='')),
                ('match_keyword', models.CharField(max_length=255)),
                ('match_definition', models.TextField()),
            ],
        ),
    ]
