# Generated by Django 2.2.17 on 2021-01-25 14:33

from django.db import migrations, models
import djongo.models.fields
import matchup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', djongo.models.fields.EmbeddedField(model_container=matchup.models.MatchModel, null=True)),
                ('match_image', models.FileField(blank=True, upload_to='')),
                ('match_keyword', models.CharField(max_length=255)),
                ('match_definition', models.TextField()),
                ('match_image_one', models.FileField(blank=True, upload_to='')),
                ('match_keyword_one', models.CharField(max_length=255)),
                ('match_definition_one', models.TextField()),
                ('match_image_two', models.FileField(blank=True, upload_to='')),
                ('match_keyword_two', models.CharField(max_length=255)),
                ('match_definition_two', models.TextField()),
                ('match_image_three', models.FileField(blank=True, upload_to='')),
                ('match_keyword_three', models.CharField(max_length=255)),
                ('match_definition_three', models.TextField()),
                ('match_image_four', models.FileField(blank=True, upload_to='')),
                ('match_keyword_four', models.CharField(max_length=255)),
                ('match_definition_four', models.TextField()),
            ],
        ),
    ]
