# Generated by Django 2.2.17 on 2021-01-28 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('img_key', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to=''), size=None)),
                ('definition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('mat_name', models.CharField(max_length=100)),
            ],
        ),
    ]



